import TradeLicenseScreen from "screens/dashboardScreens/documentsScreens/TradeLicenseScreen"

export const ROUTES = {
  HomeScreen: "home",
  WelcomeScreen: "welcome",
  FeaturesScreen: "features",
  AuthScreen: "auth",
  LogInScreen: "log-in",
  SignUpScreen: "sign-up",
  SignInEmailScreen: "sign-in-email",
  SignUpEmailScreen: "sign-up-email",
  AllServicesScreen: "all-services",
  ServiceDetailScreen: "service-detail",
  EmailVerifyScreen: "email-verify",
  RegistrationFlowScreen: "registration-flow",
  TermsConditionScreen: "terms-conditions",
  CongratulationScreen: "congratulation",
  PasswordResetScreen: "password-reset",
  RequestAddingServiceScreen: "request-adding-service",
  LeadsScreen: "leads",
  OpportunitiesScreen: "opportunities",
  MessagesScreen: "messages",
  DashboardScreen: "dashboard",
  SettingScreen: "setting",
  PasswordResetCodeScreen: "password-reset-code",
  PasswordChangeScreen: "password-change",
  NotificationsScreen: "notifications",
  ScoreDetailScreen: "score-detail",
  MyServicesScreen: "my-services",
  MyServiceDetailScreen: "my-services-detail",
  PlaceOfServiceScreen: "place-of-services",
  DeliveryRadiusScreen: "delivery-radius",
  ServiceSetupScreen: "service-setup",
  ServiceSetupFoodScreen: "service-setup-food",
  FoodCategoryScreen: "food-category",
  FoodMenuScreen: "food-menu",
  FoodSectionDetailScreen: "food-section-detail",
  FoodSectionMenuItemDetailScreen: "food-section-menu-detail",
  MyDocumentsScreen: "my-documents",
  MyDocumentsHealthScreen: "my-documents-health",
  SimilarServiceScreen: "similar-service",
  FilterScreen: "filter",
  FilterCategoriesScreen: "filter-categories",
  FilterCitiesScreen: "filter-cities",
  OpportunityDetailScreen: "opportunity-detail",
  FoodDeliveryChargeScreen: "food-delivery-charge",
  FoodDiscountsScreen: "food-discounts",
  TradeLicenseScreen: "trade-license",
  WaitScreen: "wait",
  PreviewScreen: "preview",
  FoodMenuStoreScreen: "food-menu-store",
  InterviewScreen: "interview",
  MyDocumentsBussinessDetailScreen: "my-documents-bussiness-detail",
  MyDocumentsChangePlaceScreen: "my-documents-change-place",
  MyDocumentsIdentityScreen: "my-documents-identity",
  MyDocumentsIDScreen: "my-documents-id",
  CameraScreen: "camera",
  MyDocumentsSelfieScreen: "my-documents-selfie",
  OpportunitiesSendOfferScreen: "opportunities-send-offer",
  MyPointsScreen: "my-points",
  MyPointsPackagesScreen: "my-points-packages",
  MyPointsVouchers: "my-points-vouchers",
  MyPointsTransactionsScreen: "my-points-transactions",
  AccountUpgradesScreen: "account-upgrades",
  AccountUpgradesSelectOptionsScreen: "account-upgrades-select-options",
  MyPerfomanceScreen: "my-perfomance",
} as const

type valueof<T> = T[keyof T]

export type Routes = valueof<typeof ROUTES>
